### PR TITLE
Update: add errorOnUnmatchedPattern to CLIEngine

### PR DESCRIPTION
**Pull request by arthurdenner**
Option was added on https://github.com/eslint/eslint/pull/12377.

### CODE REVIEW

**Comment by arthurdenner** [comment]
It doesn't seem like the errors are related to my changes, but let me know if I did something wrong.

**Comment by kaicataldo** [comment]
Thanks for the PR! We copy over the documentation from the github.com/eslint/eslint repository when we run a release - would you mind making a PR in that repo? [Here's](https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md) the file in question.

**Comment by arthurdenner** [comment]
@kaicataldo, there you go: https://github.com/eslint/eslint/pull/12834. Thanks for pointing it out.

**Comment by kaicataldo** [comment]
Thank you!

**Pull request closed without merging**
