### PR TITLE
New: Add Ethical Ads

### PR DESCRIPTION
**Pull request by nzakas**
This ads Ethical Ads to each page (also removes the banner). The fallback if there is no ad, or if JS is disabled, is to show an ad for sponsoring ESLint.

I have an open question to them about how the ad looks on the homepage as it seems there's some weirdness with the CSS not being caused by us.

### CODE REVIEW

**Comment by kaicataldo** [comment]
I know this is a WIP - so this might be in the pipeline - but the layout on a few other pages looks a little wonky with the floated ad container as well:

Team page:
Screen Shot 2020-08-12 at 11 46 31 PM

Sponsors page:
Screen Shot 2020-08-12 at 11 45 30 PM

**Comment by nzakas** [comment]
@btmills yeah, that's the homepage weirdness I was talking about. I figured out how to fix it. For the others, if you are only seeing the sponsorship fallback, it's possible you have an ad blocker on your browser. The sponsorship fallback will only be shown if the ad doesn't load for some reason.

@kaicataldo oops, missed those pages. I'll take a look.

**Comment by nzakas** [comment]
Okay, this should be set now. Thanks for the feedback.

**Comment by kaicataldo** [comment]
LGTM! I don't there's enough contrast with the ad on the hero of the home page, but that's an existing problem with the current header text as well. Maybe we can find an alternate background image (or scrap the image altogether), but that shouldn't block this.

**Comment by nzakas** [comment]
Okay, I’ll plan on merging on Monday so we can finalize the setup. No sense in having three days of placeholder ads on the site over the weekend.

**Pull request merged**
