### PR TITLE
Update: Fix typo

### PR DESCRIPTION
**Pull request by weihao**

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
it is a history version, and has been fixed the latest version. we usually do not change the history docs, but I think it's no harm to fix it.

**Comment by weihao** [comment]
> it is a history version, and has been fixed the latest version. we usually do not change the history docs, but I think it's no harm to fix it.

Is the latest version deployed? I am seeing from the live site: https://eslint.org/docs/2.0.0/rules/semi#options

**Comment by aladdin-add** [comment]
https://eslint.org/docs/rules/semi#options

**Comment by nzakas** [comment]
We can fix it, but really, no one should be using these old docs at this point. They are too far out of date. At some point we might just want to remove them.

**Comment by nzakas** [comment]
@weihao in order to merge this, can you please sign our [CLA](https://cla.js.foundation/eslint/website?pullRequest=854)?

**Comment by weihao** [comment]
> @weihao in order to merge this, can you please sign our [CLA](https://cla.js.foundation/eslint/website?pullRequest=854)?

Signed, thanks.

**Comment by weihao** [comment]
> We can fix it, but really, no one should be using these old docs at this point. They are too far out of date. At some point we might just want to remove them.

This page was ranked first when my googled docs for eslint, so I thought it was relevant.

It is a great idea to remove them, however, until that happens, any error should be fixed.

**Comment by nzakas** [comment]
@weihao do you remember what you searched for? And which Google site did you use?

**Comment by weihao** [comment]
> @weihao do you remember what you searched for? And which Google site did you use?

google.com, searched for `eslint semi`

**Comment by nzakas** [comment]
Very strange. I wonder if it’s related to the country you’re searching from because I’m not seeing any results for old ESLint versions. 

I’ll dig into it more later.

**Comment by weihao** [comment]
> Very strange. I wonder if it’s related to the country you’re searching from because I’m not seeing any results for old ESLint versions.
> 
> I’ll dig into it more later.

I dug around and found that I was searching for the meaning of 2 in `semi: [2, 'never']`. so I think google associated '2' with version 2 of eslint in the context

**Pull request merged**
