### PR TITLE
Update: use icons instead of text in the footer links (fixes #781)

### LINKED ISSUE #781: Using Icons insted of text-links
I guess icons will look pretty much better than text-links...
eslint

### PR DESCRIPTION
**Pull request by Pratyush-Saxena**

### CODE REVIEW

**Review by anikethsaha — CHANGES_REQUESTED** [review]
Thanks for the PR 😃 

LGTM. 

how about adding `title` prop as well so that we get the to know what are they. it would be useful for those who are not familiar with the particular logo. 
I guess, simply using the old text as a title would help. 

Also, you need to fix the commit message and the PR title according to the format.

**Comment by Pratyush-Saxena** [comment]
> Thanks for the PR 
> 
> LGTM.
> 
> how about adding `title` prop as well so that we get the to know what are they. it would be useful for those who are not familiar with the particular logo.
> I guess, simply using the old text as a title would help.
> 
> Also, you need to fix the commit message and the PR title according to the format.

pls sugggest what should i name pr title and commit message

**Comment by anikethsaha** [comment]
Maybe something like this 

`Update: use icons instead of text in the footer links(fixes #781)`

**Comment by nzakas** [comment]
Don’t worry about the commit message, we can fix that when we merge it. 

Adding a title attribute to the links is a good idea. :+1:

**Comment by Pratyush-Saxena** [comment]
> Don’t worry about the commit message, we can fix that when we merge it.
> 
> Adding a title attribute to the links is a good idea.

@nzakas pls have a look to the changes you requested

**Comment by nzakas** [comment]
Looks good to me! Thanks so much. @anikethsaha what do you think?

**Comment by anikethsaha** [comment]
I was thinking of using the title attributes so that we would get the tooltip on hover effect . 
Though the current looks good to me as well.

**Comment by nzakas** [comment]
I like having the text there better, personally. If you’re ok with this can you update your review?

**Review by anikethsaha — APPROVED** [review]
LGTM

**Review by nzakas — APPROVED** [review]

**Comment by nzakas** [comment]
Thanks so much!

**Pull request merged**
